create schema llemmy;

create table llemmy.chat_log (
    id integer generated by default as identity primary key,
    session uuid not null,
    timestamp timestamp not null,
    name text not null,
    message_type varchar(25) not null,
    message text,
    stack_trace text,
    input_tokens integer,
    output_tokens integer,
    total_tokens integer,
    json json,
    deleted boolean default false not null
);