create schema llemmy;

create table llemmy.chat (
    id integer generated by default as identity primary key,
    session uuid not null,
    timestamp timestamp not null,
    name text not null,
    message_type varchar(25) not null,
    message text,
    stack_trace text,
    response_time integer,
    input_tokens integer,
    output_tokens integer,
    total_tokens integer,
    json json,
    deleted boolean default false not null
);

comment on column llemmy.chat.session is 'Identifies the chat session';
comment on column llemmy.chat.name is 'The chat participant name';
comment on column llemmy.chat.response_time is 'The AI response time in milliseonds';
comment on column llemmy.chat.input_tokens is 'The input token count';
comment on column llemmy.chat.output_tokens is 'The output token count';
comment on column llemmy.chat.total_tokens is 'The total token count';
comment on column llemmy.chat.json is 'The message in JSON format';
comment on column llemmy.chat.deleted is 'True if the row has been soft-deleted';